### ISSUE TITLE
upvalue bug

### ISSUE THREAD

**Issue by vandiel01** [pontusm/ReputationBars#3]
Been using RepBar before pre-patch and now... getting this error after the update:

> 2x Interface/AddOns/ReputationBars/Modules/AutoBars.lua:332: attempt to index upvalue 'db' (a nil value)
> [string "@Interface/AddOns/ReputationBars/Modules/AutoBars.lua"]:332: in function `overrideInactiveReputations'
> [string "@Interface/AddOns/ReputationBars/ReputationBars.lua"]:291: in function `?'
> [string "@Interface/AddOns/BagSync/libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <...ce/AddOns/BagSync/libs/AceTimer-3.0/AceTimer-3.0.lua:50>

**Comment by karpana** [comment]
Hello @vandiel01 
Thanks for the report.

I have a few questions
1) What version of Reputation Bars are you running?
2) What version of Reputation Bars were you running before this error appeared?
3) What other addons are you running (I see BagSync referenced in the error above)?
4) Does this error still occur when Reputation Bars is the *only* addon running?

The reason I'm asking, is that the ACE3 libraries had to be updated to support Dragonflight, and I suspect that there might be an addon that is loading earlier putting an incompatible version of the ACE3 libraries in memory.

**Comment by vandiel01** [comment]
I'll check ANY addon that may use ACExx and go from there.

I pulled RepBar from this github, vers 10.0.0 with "Oct 27 2022" as last date in TOC.  I was running older RepBar from the original author on curgeforge before pre-patch.

**Comment by karpana** [comment]
Thank you Vandiel01.
I'm curious as to what might be causing this, as I"m unable to duplicate it.
The reason I picked on ACE3 "funkiness" is that the internal database (for options and configuration) is wholly run through the ACE3 DB Options capabilities, so it's super odd that that one specific pathway is failing/breaking as you've presented.


Just out of curiousity.
Did you pull from the curseforge site (aka ReputationBars-10.0.0-0007.zip) or from this github repo?

I only ask, because the github repo is usually a few updates/fixes ahead of curseforge, though I don't think there's anything in this repo that isn't in 10.0.0-0007 at this time.

**Comment by vandiel01** [comment]
I will continue to investigate on this end (IRL stuff keep coming up) and keep ya posted...

**Comment by karpana** [comment]
Adding the following sourcefourge issues into scope
[https://www.curseforge.com/wow/addons/reputation-bars/issues/2](https://www.curseforge.com/wow/addons/reputation-bars/issues/2)
[https://www.curseforge.com/wow/addons/reputation-bars/issues/3](https://www.curseforge.com/wow/addons/reputation-bars/issues/3)

**Comment by karpana** [comment]
Initial thoughts and observations
1) this is either an issue with an incompatible version of ACE3, though this begs the question why the addon is working at all.
2) this is a weird race condition that is causing the specific function to be called before the ACE3 DB handler has loaded the database.

going to attempt to put an error handler/wrapper around this call, if only to insulate the problem, as I'm unable to duplicate it.

**Comment by karpana** [comment]
@vandiel01 

As noted previously, I'm unable to duplicate the issue you're observing.  However, I've release and update [ReputationBars-10.0.2-0009.zip](https://www.curseforge.com/wow/addons/reputation-bars/files/4120112) with an error handler, that hopefully makes the error no longer occur.
Please download this version and advise if the issue has gone away.

I will close this issue report in 7 days, on the assumption this is fixed, if I don't hear anything to advise otherwise.

**Comment by karpana** [comment]
Issues from others indicate that this has been resolved.
Closing this issue.
